import os
import re
import json
import zipfile
import tempfile
import textwrap
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional

class Exporter:
    """تصدير التوثيق لصيغ متعددة"""
    
    CSS = """
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #1a1a2e; color: #e0e0e0; padding: 40px; line-height: 1.8; }
    h1 { color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
    h2 { color: #a78bfa; margin-top: 30px; }
    h3 { color: #c4b5fd; }
    code { background: #2d2d3f; padding: 4px 8px; border-radius: 4px; color: #f472b6; }
    pre { background: #0f0f1a; padding: 20px; border-radius: 8px; border: 1px solid #333; overflow-x: auto; }
    pre, code { direction: ltr; text-align: left; }
    pre code { background: none; padding: 0; color: #e0e0e0; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th { background: #7c3aed; color: #fff; padding: 10px; }
    td { padding: 10px; border: 1px solid #333; }
    tr:nth-child(even) { background: #1e1e36; }
    a { color: #7c3aed; }
    """
    
    FONT_PATHS = [
        '/data/data/com.termux/files/usr/share/fonts/TTF/DejaVuSans.ttf',
        '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
        '/usr/share/fonts/TTF/DejaVuSans.ttf',
        '/System/Library/Fonts/Helvetica.ttc',
        '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf',
    ]
    
    def __init__(self, docs: Dict[str, str], metadata: Optional[Dict] = None):
        self.docs = docs
        self.metadata = metadata or {}
        self.project = self.metadata.get('project_name', 'Project')
        self.version = self.metadata.get('version', '1.0.0')
        self.timestamp = self.metadata.get('generated_at', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    
    def _find_font(self) -> Optional[str]:
        """البحث عن خط متوفر على النظام"""
        for p in self.FONT_PATHS:
            if os.path.exists(p):
                return p
        return None
    
    def export_markdown(self, doc_type: str = 'readme') -> str:
        """تصدير Markdown خام"""
        return self.docs.get(doc_type, '')
    
    def export_all_markdown(self) -> str:
        """دمج كل الملفات في Markdown واحد"""
        parts = []
        for name, content in self.docs.items():
            if content:
                parts.append(f"# {name}\n\n{content}\n\n---\n")
        return '\n'.join(parts)
    
    def export_html(self, doc_type: str = 'readme') -> str:
        """تحويل Markdown لـ HTML مع CSS مدمج"""
        try:
            import markdown
            md_content = self.docs.get(doc_type, '')
            html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code', 'codehilite'])
            return f"""<!DOCTYPE html>
<html dir="rtl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{self.project} - {doc_type}</title>
<style>{self.CSS}</style>
</head>
<body>
<h1>{self.project} - {doc_type.upper()}</h1>
<p><em>Generated: {self.timestamp}</em></p>
<hr>
{html_body}
<hr>
<p><small>Generated by Doc Generator v{self.version}</small></p>
</body>
</html>"""
        except ImportError:
            return f"<pre>{self.docs.get(doc_type, '')}</pre>"
    
    def export_all_html(self) -> str:
        """تصدير كل الملفات كـ HTML واحد"""
        try:
            import markdown
            parts = []
            for name, content in self.docs.items():
                if content:
                    parts.append(f"<h1>{name}</h1>")
                    parts.append(markdown.markdown(content, extensions=['tables', 'fenced_code']))
                    parts.append("<hr>")
            html_body = '\n'.join(parts)
            return f"""<!DOCTYPE html>
<html dir="rtl">
<head>
<meta charset="UTF-8"><title>{self.project} - Docs</title>
<style>{self.CSS}</style>
</head>
<body>
<h1>{self.project} - Documentation</h1>
<p><em>Generated: {self.timestamp}</em></p>
<hr>
{html_body}
</body>
</html>"""
        except ImportError:
            return "<pre>Markdown library not available</pre>"
    
    def export_pdf(self, doc_type: str = 'readme', output_path: str = None) -> dict:
        """تصدير PDF - يرجع dict موحد"""
        if not output_path:
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as f:
                output_path = f.name
        
        html = self.export_html(doc_type)
        
        # 1. weasyprint
        try:
            from weasyprint import HTML
            HTML(string=html).write_pdf(output_path)
            size = os.path.getsize(output_path)
            return {"success": True, "path": output_path, "size": size, "method": "weasyprint"}
        except (ImportError, Exception):
            pass
        
        # 2. pdfkit
        try:
            import pdfkit
            pdfkit.from_string(html, output_path)
            size = os.path.getsize(output_path)
            return {"success": True, "path": output_path, "size": size, "method": "pdfkit"}
        except (ImportError, Exception):
            pass
        
        # 3. fpdf2
        result = self._pdf_with_fpdf2(doc_type, output_path)
        if result:
            return result
        
        return {"success": False, "error": "No PDF library available. Install: weasyprint, pdfkit, or fpdf2"}
    
    def _pdf_with_fpdf2(self, doc_type: str, output_path: str) -> Optional[dict]:
        """PDF باستخدام fpdf2"""
        try:
            from fpdf import FPDF
        except ImportError:
            return None
        
        font_path = self._find_font()
        pdf = FPDF()
        pdf.add_page()
        
        if font_path:
            pdf.add_font('Custom', '', font_path, )
            font_name = 'Custom'
        else:
            font_name = 'Helvetica'
        
        pdf.set_font(font_name, '', 16)
        pdf.cell(0, 10, f'{self.project} - {doc_type.upper()}', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(font_name, '', 10)
        pdf.cell(0, 10, f'Generated: {self.timestamp}', new_x="LMARGIN", new_y="NEXT")
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        content = self.docs.get(doc_type, '')
        pdf.set_font(font_name, '', 12)
        
        for line in content.split('\n'):
            clean = re.sub(r'[`*#]', '', line).strip()
            if clean:
                wrapped = textwrap.fill(clean, width=100)
                for segment in wrapped.split('\n'):
                    try:
                        pdf.multi_cell(0, 8, segment)
                    except:
                        pass
        
        pdf.output(output_path)
        size = os.path.getsize(output_path)
        return {"success": True, "path": output_path, "size": size, "method": "fpdf2"}
    
    def export_zip(self, output_path: str = None) -> dict:
        """تصدير ZIP - يرجع dict موحد"""
        if not output_path:
            with tempfile.NamedTemporaryFile(suffix='.zip', delete=False) as f:
                output_path = f.name
        
        try:
            with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zf:
                for name, content in self.docs.items():
                    if content:
                        safe_name = name.replace('/', '_').replace('\\', '_')
                        zf.writestr(f"markdown/{safe_name}.md", content)
                        try:
                            html = self.export_html(name)
                            zf.writestr(f"html/{safe_name}.html", html)
                        except:
                            pass
                
                all_md = self.export_all_markdown()
                zf.writestr("README.md", all_md)
                zf.writestr("metadata.json", json.dumps({
                    **self.metadata,
                    'exported_at': datetime.now().isoformat(),
                    'files': list(self.docs.keys())
                }, indent=2, ensure_ascii=False))
            
            size = os.path.getsize(output_path)
            return {"success": True, "path": output_path, "size": size}
        except Exception as e:
            return {"success": False, "error": str(e)}

def export_docs(docs: Dict[str, str], metadata: Optional[Dict] = None) -> Exporter:
    """دالة مساعدة سريعة"""
    return Exporter(docs, metadata)

if __name__ == "__main__":
    print("Testing Exporter...")
    
    sample = {
        "README": "# Test Project\n\nوصف المشروع هنا\n\n## Features\n- feature 1\n- feature 2",
        "API_DOCS": "## API Documentation\n\n### get_data()\nReturns data",
        "CHANGELOG": "# Changelog\n\n## v1.0\n- First release"
    }
    
    meta = {"project_name": "TestProject", "version": "1.0.0"}
    exporter = Exporter(sample, meta)
    
    md = exporter.export_markdown("README")
    print(f"Markdown: {len(md)} chars")
    
    html = exporter.export_html("README")
    print(f"HTML: {len(html)} chars")
    
    pdf = exporter.export_pdf("README")
    print(f"PDF: {pdf}")
    
    zip_result = exporter.export_zip()
    print(f"ZIP: {zip_result}")
    
    print("Done")
