import os
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

VERSION = "2.0.0"

class TemplateEngine:
    @staticmethod
    def get_badge(label, message, color="blue"):
        return f"![{label}](https://img.shields.io/badge/{label}-{message}-{color})"
    
    @staticmethod
    def get_table(headers, rows):
        r = "| " + " | ".join(headers) + " |\n"
        r += "|" + "|".join(["------" for _ in headers]) + "|\n"
        for row in rows:
            r += "| " + " | ".join(str(c) for c in row) + " |\n"
        return r
    
    @staticmethod
    def get_code_block(code, language="python"):
        return f"```{language}\n{code}\n```"
    
    @staticmethod
    def get_alert(text, alert_type="info"):
        icons = {"info": "i", "warning": "!", "tip": "*", "danger": "x", "success": "+"}
        icon = icons.get(alert_type, "i")
        return f"> [{icon}] {text}"
    
    @staticmethod
    def get_section(title, content, level=2):
        prefix = "#" * level
        return f"\n{prefix} {title}\n\n{content}\n"

class QualityChecker:
    @staticmethod
    def check_readme(content):
        score = 0
        checks = []
        sections = {"description": 1.5, "installation": 1.5, "usage": 1.5, "features": 1.5, "requirements": 0.5, "license": 0.5, "contributing": 0.5, "stats": 0.5}
        cl = content.lower()
        for s, p in sections.items():
            if s in cl or s in cl:
                score += p
                checks.append(f"+ {s}")
            else:
                checks.append(f"- {s}")
        if "```" in content: score += 0.5; checks.append("+ code")
        if "|" in content: score += 0.5; checks.append("+ table")
        if len(content) > 500: score += 0.5; checks.append("+ length")
        score = min(score, 10)
        grade = "A+" if score >= 9 else "A" if score >= 8 else "B" if score >= 6 else "C" if score >= 4 else "D"
        return {"score": score, "grade": grade, "checks": checks}

T = TemplateEngine()

def generate_readme_advanced(analysis, style="formal", language="ar", project_name="My Project", description="", author="Doc Generator AI", repo_url="", license_type="MIT"):
    stats = analysis.get("complexity", {})
    functions = analysis.get("functions", [])
    classes = analysis.get("classes", [])
    lang = analysis.get("language", "Python")
    
    if language == "en":
        TXT = {"overview": "Overview", "features": "Features", "install": "Installation", "usage": "Usage", "stats": "Project Stats", "reqs": "Requirements", "license": "License", "desc_default": "Project", "warn": "Make sure all requirements are installed", "licensed": "Licensed under", "gen": "Auto-generated by Doc Generator", "date": "Date"}
    else:
        TXT = {"overview": "نظرة عامة", "features": "الميزات", "install": "التثبيت", "usage": "الاستخدام", "stats": "إحصائيات المشروع", "reqs": "المتطلبات", "license": "الرخصة", "desc_default": "مشروع", "warn": "تأكد من تثبيت جميع المتطلبات قبل التشغيل", "licensed": "هذا المشروع مرخص تحت رخصة", "gen": "تم توليد هذا الملف تلقائيا بواسطة Doc Generator", "date": "التاريخ"}
    
    lines = []
    lines.append(f"# {project_name}")
    lines.append("")
    lines.append(T.get_badge("Version", VERSION, "blue"))
    lines.append(T.get_badge("Language", lang, "green"))
    lines.append(T.get_badge("License", license_type, "yellow"))
    lines.append("")
    lines.append(T.get_section(f"{TXT['overview']}", description or f"{TXT['desc_default']} {project_name}"))
    
    lines.append(T.get_section(f"{TXT['features']}", ""))
    for func in functions[:10]:
        lines.append(f"- `{func.get('name','')}`")
    for cls in classes[:5]:
        lines.append(f"- `{cls.get('name','')}`")
    
    lines.append(T.get_section(f"{TXT['install']}", T.get_code_block("pip install -r requirements.txt", "bash")))
    lines.append(T.get_section(f"{TXT['usage']}", T.get_code_block("import module", "python")))
    lines.append(T.get_alert(TXT['warn'], "info"))
    
    lines.append(T.get_section(f"{TXT['stats']}", T.get_table(["Item", "Count"], [["Lines", str(stats.get("total_lines",0))], ["Functions", str(len(functions))], ["Classes", str(len(classes))]])))
    lines.append(T.get_section(f"{TXT['reqs']}", "- Standard library"))
    lines.append(T.get_section(f"{TXT['license']}", f"{TXT['licensed']} **{license_type}**"))
    lines.append(f"---\n*{TXT['gen']}*\n*{TXT['date']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    
    return "\n".join(lines)

def generate_api_docs_advanced(analysis, style="tech", language="ar"):
    functions = analysis.get("functions", [])
    classes = analysis.get("classes", [])
    lang = analysis.get("language", "Python")
    
    if language == "en":
        TXT = {"functions": "Functions", "classes": "Classes", "nofunc": "No functions", "noclass": "No classes", "line": "Line", "params": "Parameters", "returns": "Returns", "yes": "Yes", "no": "No", "desc": "Description", "gen": "Generated"}
    else:
        TXT = {"functions": "الدوال", "classes": "الكلاسات", "nofunc": "لا توجد دوال", "noclass": "لا توجد كلاسات", "line": "السطر", "params": "المعلمات", "returns": "القيمة المرجعة", "yes": "نعم", "no": "لا", "desc": "الوصف", "gen": "تم التوليد"}
    
    lines = []
    lines.append(f"# {analysis.get('filename','Project')} - API Documentation")
    lines.append(T.get_badge("Language", lang, "green"))
    lines.append(T.get_badge("Functions", str(len(functions)), "blue"))
    lines.append("---")
    
    lines.append(f"## {TXT['functions']}")
    if functions:
        for func in functions:
            lines.append(f"### `{func['name']}({', '.join(func.get('args',[]))})`")
            lines.append(f"- {TXT['line']}: {func.get('lineno','?')}")
            lines.append(f"- {TXT['returns']}: {TXT['yes'] if func.get('has_return') else TXT['no']}")
            if func.get('docstring'): lines.append(f"- {TXT['desc']}: {func['docstring']}")
            lines.append("---")
    else:
        lines.append(TXT['nofunc'])
    
    lines.append(f"## {TXT['classes']}")
    if classes:
        for cls in classes:
            lines.append(f"### class {cls['name']}")
            lines.append("---")
    else:
        lines.append(TXT['noclass'])
    
    lines.append(f"*{TXT['gen']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    return "\n".join(lines)

def generate_wiki(analysis, language="ar"):
    functions = analysis.get("functions", [])
    classes = analysis.get("classes", [])
    lang = analysis.get("language", "Python")
    
    if language == "en":
        T = {"title": "Project Wiki", "overview": "Overview", "functions": "Functions Guide", "classes": "Classes Guide", "usage": "Usage Examples", "getting_started": "Getting Started", "desc": "Description"}
    else:
        T = {"title": "دليل المشروع", "overview": "نظرة عامة", "functions": "دليل الدوال", "classes": "دليل الكلاسات", "usage": "أمثلة استخدام", "getting_started": "بداية سريعة", "desc": "الوصف"}
    
    lines = []
    lines.append(f"# {T['title']}")
    lines.append("")
    lines.append(f"## {T['overview']}")
    lines.append(f"هذا المشروع مكتوب بلغة **{lang}** ويحتوي على **{len(functions)}** دالة و **{len(classes)}** كلاس.")
    lines.append("")
    
    if functions:
        lines.append(f"## {T['functions']}")
        lines.append("")
        for func in functions[:20]:
            name = func.get("name", "")
            doc = func.get("docstring", "")
            desc = doc.split("\n")[0] if doc else T["desc"]
            args = ", ".join(func.get("args", []))
            lines.append(f"### `{name}({args})`")
            lines.append(f"{desc}")
            lines.append("")
    
    if classes:
        lines.append(f"## {T['classes']}")
        lines.append("")
        for cls in classes[:10]:
            name = cls.get("name", "")
            doc = cls.get("docstring", "")
            methods = cls.get("methods", [])
            lines.append(f"### `class {name}`")
            if doc: lines.append(f"{doc.split(chr(10))[0]}")
            if methods:
                lines.append(f"الطرق: {', '.join(['`'+m['name']+'()`' for m in methods])}")
            lines.append("")
    
    lines.append(f"## {T['usage']}")
    lines.append("```python")
    lines.append("import module")
    if functions:
        f = functions[0]
        lines.append(f"result = {f['name']}()")
    lines.append("```")
    lines.append("")
    lines.append(f"## {T['getting_started']}")
    lines.append("1. تثبيت المتطلبات: `pip install -r requirements.txt`")
    lines.append("2. استيراد المكتبات المطلوبة")
    lines.append("3. استخدام الدوال والكلاسات حسب الحاجة")
    
    return "\n".join(lines)

def generate_changelog(analysis, version="1.0.0"):
    functions = analysis.get("functions", [])
    classes = analysis.get("classes", [])
    
    lines = []
    lines.append("# 📝 Changelog")
    lines.append("")
    lines.append("All notable changes to this project will be documented in this file.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"## [{version}] - {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("")
    
    if functions:
        lines.append("### ✨ Added")
        for func in functions[:10]:
            doc = func.get("docstring", "")
            desc = doc.split("\n")[0] if doc else f"New function"
            lines.append(f"- `{func['name']}()` - {desc[:80]}")
        lines.append("")
    
    if classes:
        lines.append("### 🏗️ Added")
        for cls in classes[:5]:
            doc = cls.get("docstring", "")
            desc = doc.split("\n")[0] if doc else "New class"
            lines.append(f"- `class {cls['name']}` - {desc[:80]}")
        lines.append("")
    
    lines.append("### 📊 Stats")
    lines.append(f"- Total functions: {len(functions)}")
    lines.append(f"- Total classes: {len(classes)}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## [Unreleased]")
    lines.append("### 🔧 Changed")
    lines.append("- Auto-generated documentation update")
    lines.append("### 🐛 Fixed")
    lines.append("- Continuous improvements")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## [0.1.0] - Initial")
    lines.append("### ✨ Added")
    lines.append("- Project structure")
    lines.append("- Core functionality")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Format based on [Keep a Changelog](https://keepachangelog.com/)*")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    
    return "\n".join(lines)

def generate_all_docs(source_code, analysis, project_name="My Project", style="formal", language="ar", doc_types=None):
    if doc_types is None:
        doc_types = ["readme", "api", "wiki", "changelog"]
    result = {}
    if "readme" in doc_types:
        result["README.md"] = generate_readme_advanced(analysis, style, language, project_name)
    if "api" in doc_types:
        result["API_DOCS.md"] = generate_api_docs_advanced(analysis, style, language)
    if "wiki" in doc_types:
        result["WIKI.md"] = generate_wiki(analysis, language)
    if "changelog" in doc_types:
        result["CHANGELOG.md"] = generate_changelog(analysis)
    return result

def get_quality_report(docs):
    report = {}
    for name, content in docs.items():
        if "README" in name:
            report[name] = QualityChecker.check_readme(content)
    return report

if __name__ == "__main__":
    print("Generator ready")
